<?php
namespace Espo\Modules\EndlessDreamTravel\Classes\RecordHooks\Booking;

use Espo\Core\Record\Hook\SaveHook;
use Espo\ORM\Entity;
use Espo\ORM\EntityManager;

class EnsureCommissionRecord implements SaveHook
{
    public function __construct(private EntityManager $entityManager)
    {}

    public function process(Entity $booking): void
    {
        if (!$booking->hasId()) {
            return;
        }

        $expectedAmount = (float) ($booking->get('expectedCommission') ?? 0);
        if ($expectedAmount <= 0) {
            return;
        }

        $repository = $this->entityManager->getRDBRepository('EdtCommission');
        $automaticCommission = $repository
            ->where([
                'bookingId' => $booking->getId(),
                'autoGenerated' => true,
            ])
            ->findOne();

        if (!$automaticCommission) {
            $existingBaseCommission = $repository
                ->where([
                    'bookingId' => $booking->getId(),
                    'type' => 'Base Commission',
                ])
                ->findOne();

            if ($existingBaseCommission) {
                return;
            }

            $automaticCommission = $this->entityManager->getNewEntity('EdtCommission');
            $automaticCommission->set([
                'name' => substr('COMM - ' . (string) $booking->get('name'), 0, 180),
                'bookingId' => $booking->getId(),
                'supplierId' => $booking->get('supplierId'),
                'type' => 'Base Commission',
                'status' => 'Expected',
                'autoGenerated' => true,
            ]);
        }

        $automaticCommission->set([
            'name' => substr('COMM - ' . (string) $booking->get('name'), 0, 180),
            'expectedAmount' => $expectedAmount,
            'expectedAmountCurrency' => $booking->get('expectedCommissionCurrency'),
            'supplierId' => $booking->get('supplierId'),
        ]);

        $this->entityManager->saveEntity($automaticCommission);
    }
}
